- name: Windows Standaard
  hosts: "{{ host_group }}"
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names: 
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        reboot: yes
        
    - name: Upgrade installed packages
      win_chocolatey:
        name: all
        state: latest
        
    - name: disable enhanced exit codes
      win_chocolatey_feature:
        name: useEnhancedExitCodes
        state: disabled
        
  
  
    - name: Set Pagefile
      win_pagefile:
        drive: C
        initial_size: 2048
        maximum_size: 2048
        state: present
        automatic: no

    - name: Set Windows Region
      win_region:
        format: nl-NL
        copy_settings: true
        location: 176
        unicode_language: nl-NL
      register: region

    - name: Reboot for Region Settings
      win_reboot:
      when: region.restart_required

    - name: Change the Powerplan to High Performance
      win_power_plan:
        name: high performance
